test: trap build errors and revert dist

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,12 +40,18 @@ jobs:
             if [ -f "${ACTION_DIR}package.json" ]; then
               (
                 cd "${ACTION_DIR}"
-                trap 'echo "build or test failed, reverting ..."; git checkout HEAD -- "'${ACTION_DIR}'dist"' 2>/dev/null || true
+
+                trap '
+                  echo "❌ command failed in ${ACTION_DIR}, reverting build ..."
+                  git checkout HEAD -- ${ACTION_DIR}dist/ 2>/dev/null || true
+                  git clean -fd ${ACTION_DIR}dist/ 2>/dev/null || true
+                ' ERR
+
                 npm ci
                 npm run prebuild
                 npm run build
                 npm run test
-              )
+              ) || echo "⚠️ building action ${ACTION%/} failed, skipping"
             fi
           done
 
